var redditData = {
"kind": "Listing",
"data": {
"modhash": "9ohoh2f3tq6678e3e27eef0c0e1c89917c68bad7f0c85ae5b5",
"children": [
{
"kind": "t3",
"data": {
"domain": "i.imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "394ws9",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "michaelconfoy",
"media": null,
"score": 24,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 2,
"thumbnail": "http://b.thumbs.redditmedia.com/EOS3pGHk5fZYeX0CQr0ts9qvMuO7ZuSXfTu3Vl2epSE.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/394ws9/charleston_college_charleston_south_carolina_1901/",
"name": "t3_394ws9",
"created": 1433864519,
"url": "http://i.imgur.com/O4l4fi1.jpg",
"author_flair_text": null,
"title": "Charleston College, Charleston, South Carolina, 1901.",
"created_utc": 1433835719,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 24
}
},
{
"kind": "t3",
"data": {
"domain": "i.imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "391vms",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "TJBPhoto",
"media": null,
"score": 41,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 8,
"thumbnail": "http://b.thumbs.redditmedia.com/euCNGxVvYkOkPTQ6pc3WwDKIRS_okqDGaFhEI69ZIdE.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/391vms/lost_gopro_making_its_rounds_on_facebook_i/",
"name": "t3_391vms",
"created": 1433813076,
"url": "http://i.imgur.com/oQx3QJc.png",
"author_flair_text": null,
"title": "Lost Gopro making its rounds on Facebook, I figured I'd post here for added visibility",
"created_utc": 1433784276,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 41
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Can anyone recommend a doctor for lasik eye surgery in the area?  Trying to do my due diligence.  Thanks. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Can anyone recommend a doctor for lasik eye surgery in the area?  Trying to do my due diligence.  Thanks. ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "394i3k",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "killakoda",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 6,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/394i3k/lasik_in_charleston/",
"name": "t3_394i3k",
"created": 1433855120,
"url": "http://www.reddit.com/r/Charleston/comments/394i3k/lasik_in_charleston/",
"author_flair_text": null,
"title": "Lasik in Charleston?",
"created_utc": 1433826320,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "vimeo.com",
"banned_by": null,
"media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F58118568&amp;url=https%3A%2F%2Fvimeo.com%2F58118568&amp;image=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F461949685_1280.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vimeo\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 338
},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": {
"oembed": {
"provider_url": "https://vimeo.com/",
"description": "From Palmetto Coast Media &amp; Lifesize Entertainment comes \"Give Me Shelter,\" a reality TV series about committed animal welfare advocates. Producers: Bruce Frigeri &amp; Jessie Anderson-Berens Genre: Reality / Animals Series: 13 x 30 HD Title: GIVE ME SHELTER LOGLINE: \"Animal Cops\" combines with \"Underdog To Wonder Dog\" to tell the incredible story of the Pet Helpers Animal Shelter in Charleston, SC.",
"title": "\"Give Me Shelter\" Teaser",
"type": "video",
"thumbnail_width": 1280,
"height": 338,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F58118568&amp;url=https%3A%2F%2Fvimeo.com%2F58118568&amp;image=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F461949685_1280.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vimeo\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"author_name": "Palmetto Coast Media",
"version": "1.0",
"provider_name": "Vimeo",
"thumbnail_url": "https://i.embed.ly/1/image?url=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F461949685_1280.jpg&amp;key=b1e305db91cf4aa5a86b732cc9fffceb",
"thumbnail_height": 720,
"author_url": "http://vimeo.com/palmettocoastmedia"
},
"type": "vimeo.com"
},
"link_flair_text": null,
"id": "392kvb",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "theninetyninthstraw",
"media": {
"oembed": {
"provider_url": "https://vimeo.com/",
"description": "From Palmetto Coast Media &amp; Lifesize Entertainment comes \"Give Me Shelter,\" a reality TV series about committed animal welfare advocates. Producers: Bruce Frigeri &amp; Jessie Anderson-Berens Genre: Reality / Animals Series: 13 x 30 HD Title: GIVE ME SHELTER LOGLINE: \"Animal Cops\" combines with \"Underdog To Wonder Dog\" to tell the incredible story of the Pet Helpers Animal Shelter in Charleston, SC.",
"title": "\"Give Me Shelter\" Teaser",
"type": "video",
"thumbnail_width": 1280,
"height": 338,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F58118568&amp;url=https%3A%2F%2Fvimeo.com%2F58118568&amp;image=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F461949685_1280.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vimeo\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"author_name": "Palmetto Coast Media",
"version": "1.0",
"provider_name": "Vimeo",
"thumbnail_url": "http://i.vimeocdn.com/video/461949685_1280.jpg",
"thumbnail_height": 720,
"author_url": "http://vimeo.com/palmettocoastmedia"
},
"type": "vimeo.com"
},
"score": 14,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 2,
"thumbnail": "http://b.thumbs.redditmedia.com/xfQzvJA6JCAbSXLMxvqDTG_47Eo-XpcIezMdd2DxXGA.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F58118568&amp;url=https%3A%2F%2Fvimeo.com%2F58118568&amp;image=http%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F461949685_1280.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vimeo\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 338
},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/392kvb/pet_helpers_on_james_island_gets_a_new_tv_show_on/",
"name": "t3_392kvb",
"created": 1433823175,
"url": "https://vimeo.com/58118568",
"author_flair_text": null,
"title": "Pet Helpers on James Island Gets a New TV Show on NatGeo Wild Titled \"Give Me Shelter\"",
"created_utc": 1433794375,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 14
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;My best friend is coming to town at the end of the month. She&amp;#39;s vegan and I really want to take her to some great spots. I know there&amp;#39;s a hidden one on Coleman and for the love of God, I can not remember the name of it. But, I&amp;#39;d love to hear any suggestions for some! Im on my phone and I couldn&amp;#39;t get the sidebar to come up for me to see if this has been posted before. She&amp;#39;s been a vegan since we met in elementary school, nothing gets past her fyi. Some can be really rude about it, but she&amp;#39;s always been vegan and I would really like her to enjoy her time here without always having to eat a salad :) &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "My best friend is coming to town at the end of the month. She's vegan and I really want to take her to some great spots. I know there's a hidden one on Coleman and for the love of God, I can not remember the name of it. But, I'd love to hear any suggestions for some! Im on my phone and I couldn't get the sidebar to come up for me to see if this has been posted before. She's been a vegan since we met in elementary school, nothing gets past her fyi. Some can be really rude about it, but she's always been vegan and I would really like her to enjoy her time here without always having to eat a salad :) ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3949gu",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "aintitso",
"media": null,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3949gu/need_help_finding_vegan_spots/",
"name": "t3_3949gu",
"created": 1433850438,
"url": "http://www.reddit.com/r/Charleston/comments/3949gu/need_help_finding_vegan_spots/",
"author_flair_text": null,
"title": "Need help finding vegan spots!",
"created_utc": 1433821638,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 3
}
},
{
"kind": "t3",
"data": {
"domain": "abcnews4.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "391h8l",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "beauseph",
"media": null,
"score": 14,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 0,
"thumbnail": "http://a.thumbs.redditmedia.com/NqvT9JdwOWbVHzoGG0slRAKG71-phlPSptt1Y4Rm6w8.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/391h8l/indictment_handed_down_against_officer_in_walter/",
"name": "t3_391h8l",
"created": 1433807186,
"url": "http://www.abcnews4.com/story/29263646/press-conference-planned-for-update-in-walter-scott-case",
"author_flair_text": null,
"title": "Indictment handed down against officer in Walter Scott shooting",
"created_utc": 1433778386,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 14
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I feel the title says it all. I am a little worried about finding work out here, but I like the city so far. Is there anything I should know? Anything I should avoid (I assume with all the Jesus stuff around bringing up being atheist is faux paux)?&lt;/p&gt;\n\n&lt;p&gt;The area I&amp;#39;m used to is the South West. New Mexico, El Paso, Arizona, ect.  &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I feel the title says it all. I am a little worried about finding work out here, but I like the city so far. Is there anything I should know? Anything I should avoid (I assume with all the Jesus stuff around bringing up being atheist is faux paux)?\n\nThe area I'm used to is the South West. New Mexico, El Paso, Arizona, ect.  ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3932l5",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Lpup",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 8,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3932l5/girlfriend_is_looking_into_two_fashion_jobs_in/",
"name": "t3_3932l5",
"created": 1433830417,
"url": "http://www.reddit.com/r/Charleston/comments/3932l5/girlfriend_is_looking_into_two_fashion_jobs_in/",
"author_flair_text": null,
"title": "Girlfriend is looking into two fashion jobs in the area. Love the area, want to know more about culture and how hard is would be to find a decent job with a degree in business there..",
"created_utc": 1433801617,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Anyone ever eat at The Griffon?  Haven&amp;#39;t heard of it, but I LOVE pub food, and it looks good.  Any other pub food hidden gems in the area I might not know about?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Anyone ever eat at The Griffon?  Haven't heard of it, but I LOVE pub food, and it looks good.  Any other pub food hidden gems in the area I might not know about?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38z0ty",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "charleston_guy",
"media": null,
"score": 7,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 21,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38z0ty/pub_food_question/",
"name": "t3_38z0ty",
"created": 1433755010,
"url": "http://www.reddit.com/r/Charleston/comments/38z0ty/pub_food_question/",
"author_flair_text": null,
"title": "Pub food question",
"created_utc": 1433726210,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 7
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Just curious as to what this subreddit thinks about the whole thing.....&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Just curious as to what this subreddit thinks about the whole thing.....",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3907w6",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "brophyd",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 4,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3907w6/what_does_everyone_think_on_the_duane_lewis_and/",
"name": "t3_3907w6",
"created": 1433780103,
"url": "http://www.reddit.com/r/Charleston/comments/3907w6/what_does_everyone_think_on_the_duane_lewis_and/",
"author_flair_text": null,
"title": "What does everyone think on the Duane Lewis and Brian Adams debate/discussion going on?",
"created_utc": 1433751303,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
},
{
"kind": "t3",
"data": {
"domain": "weather.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38wlkw",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "hightide13",
"media": null,
"score": 29,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 12,
"thumbnail": "http://a.thumbs.redditmedia.com/P0DvgZ85jwyuZ5VdvFkZqgMYB_KJO6anULRl7zRCAk8.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/38wlkw/group_of_folks_from_charleston_find_spacex/",
"name": "t3_38wlkw",
"created": 1433711973,
"url": "http://www.weather.com/science/space/news/spacex-wreckage-found-kevin-eichelberger?cm_ven=Twitter_TheWeatherChannel_Science_SBr_Article_No_5_20150604",
"author_flair_text": null,
"title": "Group of folks from Charleston find SpaceX wreckage in the Bahamas. Elon Musk responds to Twitter pics...",
"created_utc": 1433683173,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 29
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I am graduating from college in a year and half to become either an english or history teacher (I am getting BAs in both) and was wondering if anybody knows of a lot of job openings near Charleston? Also I was wondering if anybody knows of any schools that I should avoid that could be potentially life threatening to me. I am from Indiana and would love to move to the Goose Creek/ Charleston area with my finance! &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I am graduating from college in a year and half to become either an english or history teacher (I am getting BAs in both) and was wondering if anybody knows of a lot of job openings near Charleston? Also I was wondering if anybody knows of any schools that I should avoid that could be potentially life threatening to me. I am from Indiana and would love to move to the Goose Creek/ Charleston area with my finance! ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38zpf7",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "BamCheezit",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 12,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38zpf7/schools_in_charleston/",
"name": "t3_38zpf7",
"created": 1433767716,
"url": "http://www.reddit.com/r/Charleston/comments/38zpf7/schools_in_charleston/",
"author_flair_text": null,
"title": "Schools in Charleston",
"created_utc": 1433738916,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hello everyone!  I would love some feedback from those of you in Charleston.  I graduated with a BSN from Towson and will be taking the NCLEX in a month.  So far I am trying to apply to new grad positions at MUSC (Haven&amp;#39;t heard back), Roper St. Francis (Application not selected because I don&amp;#39;t have a current license yet) and Trident Healthcare systems.  I&amp;#39;m hoping to be selected for a floor in which I can further my foundational skills: Med-surg, IMC, PAU, etc.  Does anyone have any helpful information about these hospitals or further suggestions?  Thanks, and have a great day!  &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hello everyone!  I would love some feedback from those of you in Charleston.  I graduated with a BSN from Towson and will be taking the NCLEX in a month.  So far I am trying to apply to new grad positions at MUSC (Haven't heard back), Roper St. Francis (Application not selected because I don't have a current license yet) and Trident Healthcare systems.  I'm hoping to be selected for a floor in which I can further my foundational skills: Med-surg, IMC, PAU, etc.  Does anyone have any helpful information about these hospitals or further suggestions?  Thanks, and have a great day!  ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38xhiu",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "FutureCharlestonRN",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38xhiu/bsn_nursing_options_in_charleston/",
"name": "t3_38xhiu",
"created": 1433728862,
"url": "http://www.reddit.com/r/Charleston/comments/38xhiu/bsn_nursing_options_in_charleston/",
"author_flair_text": null,
"title": "BSN nursing options in Charleston?",
"created_utc": 1433700062,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hello all,&lt;/p&gt;\n\n&lt;p&gt;I have a few questions about moving to Charleston.  My girlfriend who is from France wants to move to the US with me.  We currently live together in Prague where I work in IT and she is getting her masters in Economics.  &lt;/p&gt;\n\n&lt;p&gt;She has given me the task of finding a place for us to live in the US.  Her requirements are it must be warm,close to the sea and have good food.  She is from the south of France so she has the best of all of the above.  I have been doing some research and I think Charleston would be a good fit for us. Are there any Europeans that live here that can chime in on this?  Is Charleston a good town for a European in America?&lt;/p&gt;\n\n&lt;p&gt;Thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hello all,\n\nI have a few questions about moving to Charleston.  My girlfriend who is from France wants to move to the US with me.  We currently live together in Prague where I work in IT and she is getting her masters in Economics.  \n\nShe has given me the task of finding a place for us to live in the US.  Her requirements are it must be warm,close to the sea and have good food.  She is from the south of France so she has the best of all of the above.  I have been doing some research and I think Charleston would be a good fit for us. Are there any Europeans that live here that can chime in on this?  Is Charleston a good town for a European in America?\n\nThanks!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38wj0o",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "MarburgDE",
"media": null,
"score": 11,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 22,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38wj0o/do_any_europeans_live_here_im_looking_for_some/",
"name": "t3_38wj0o",
"created": 1433710169,
"url": "http://www.reddit.com/r/Charleston/comments/38wj0o/do_any_europeans_live_here_im_looking_for_some/",
"author_flair_text": null,
"title": "Do any Europeans live here? I'm looking for some perspective about moving to Charleston.",
"created_utc": 1433681369,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 11
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Found a Black and white hound mix, female, middle aged running around The Farms at wescott next to the amenities center. Had an indent for a collar, she was not chipped, and someone trained it. I took her to the SPCA of dorchester on hwy 78, if it&amp;#39;s yours go get her, shes a sweet heart.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Found a Black and white hound mix, female, middle aged running around The Farms at wescott next to the amenities center. Had an indent for a collar, she was not chipped, and someone trained it. I took her to the SPCA of dorchester on hwy 78, if it's yours go get her, shes a sweet heart.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38t4ft",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "RadioHitandRun",
"media": null,
"score": 23,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 4,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38t4ft/dog_found_in_summervillenorth_charleston_area/",
"name": "t3_38t4ft",
"created": 1433611110,
"url": "http://www.reddit.com/r/Charleston/comments/38t4ft/dog_found_in_summervillenorth_charleston_area/",
"author_flair_text": null,
"title": "Dog Found in summerville/North Charleston area",
"created_utc": 1433607510,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 23
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I know this has been brought up a time or two but I drove over to Porter-Gaud like has been suggested and that track is definitely private and I can&amp;#39;t go during school hours when it might be open. Are there any true public access 1/4 mile tracks in West Ash?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I know this has been brought up a time or two but I drove over to Porter-Gaud like has been suggested and that track is definitely private and I can't go during school hours when it might be open. Are there any true public access 1/4 mile tracks in West Ash?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38tonf",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "ChaserBD04",
"media": null,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38tonf/14th_mile_outdoor_tracks_in_west_ashley/",
"name": "t3_38tonf",
"created": 1433620547,
"url": "http://www.reddit.com/r/Charleston/comments/38tonf/14th_mile_outdoor_tracks_in_west_ashley/",
"author_flair_text": null,
"title": "1/4th mile outdoor tracks in West Ashley?",
"created_utc": 1433616947,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 6
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Anyone know of any hardcore/punk/wild shows coming to the area?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Anyone know of any hardcore/punk/wild shows coming to the area?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38vbhi",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "hjwoolwine",
"media": null,
"score": 1,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 3,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38vbhi/need_to_mosh_it_out/",
"name": "t3_38vbhi",
"created": 1433676386,
"url": "http://www.reddit.com/r/Charleston/comments/38vbhi/need_to_mosh_it_out/",
"author_flair_text": null,
"title": "Need to mosh it out",
"created_utc": 1433647586,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 1
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;See title!&lt;/p&gt;\n\n&lt;p&gt;I&amp;#39;m in town solo for one more day after a family vacation in Isle of Palms. My Amtrak back to the Northeast leaves at 9:20 PM, and post time is 6:50 PM. What&amp;#39;s the best place for a mid-20s guy to have a drink and watch the race? &lt;/p&gt;\n\n&lt;p&gt;Thanks! PS -- your city is fantastic, and all of you are extremely hospitable. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "See title!\n\nI'm in town solo for one more day after a family vacation in Isle of Palms. My Amtrak back to the Northeast leaves at 9:20 PM, and post time is 6:50 PM. What's the best place for a mid-20s guy to have a drink and watch the race? \n\nThanks! PS -- your city is fantastic, and all of you are extremely hospitable. ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38tifc",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "rosten",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 0,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38tifc/best_place_downtown_to_watch_the_belmont_stakes/",
"name": "t3_38tifc",
"created": 1433617624,
"url": "http://www.reddit.com/r/Charleston/comments/38tifc/best_place_downtown_to_watch_the_belmont_stakes/",
"author_flair_text": null,
"title": "Best place downtown to watch the Belmont Stakes?",
"created_utc": 1433614024,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Preferably furnished. Pets don&amp;#39;t bother me.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Preferably furnished. Pets don't bother me.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38t7bw",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "conitsts",
"media": null,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38t7bw/inc_grad_student_need_a_12bedroom_for_600700month/",
"name": "t3_38t7bw",
"created": 1433612423,
"url": "http://www.reddit.com/r/Charleston/comments/38t7bw/inc_grad_student_need_a_12bedroom_for_600700month/",
"author_flair_text": null,
"title": "Inc grad student need a 1-2Bedroom for 600-700$/month.",
"created_utc": 1433608823,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 6
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;What&amp;#39;s the best website for swinging around here?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "What's the best website for swinging around here?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38vj4c",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "diggitydank007",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38vj4c/swingers_of_charleston/",
"name": "t3_38vj4c",
"created": 1433655695,
"url": "http://www.reddit.com/r/Charleston/comments/38vj4c/swingers_of_charleston/",
"author_flair_text": null,
"title": "Swingers Of Charleston",
"created_utc": 1433652095,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hi guys!&lt;/p&gt;\n\n&lt;p&gt;I&amp;#39;m moving to Charleston with 2 others for 2 months and I was wondering if anyone had a 2 bedroom flat they would like to lease to us? \nAll three of us are Irish and can provide references and all that good stuff, ideally we are looking to pay under $1000/month between the 3 of us, I took a look at craigslist but no one is getting back to me so far!&lt;/p&gt;\n\n&lt;p&gt;Thanks again, I can&amp;#39;t wait to move into your beautiful city :)&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hi guys!\n\n I'm moving to Charleston with 2 others for 2 months and I was wondering if anyone had a 2 bedroom flat they would like to lease to us? \nAll three of us are Irish and can provide references and all that good stuff, ideally we are looking to pay under $1000/month between the 3 of us, I took a look at craigslist but no one is getting back to me so far!\n\n\nThanks again, I can't wait to move into your beautiful city :)",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38smg2",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "mrsmellysock",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 6,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38smg2/looking_for_a_flat_downtown/",
"name": "t3_38smg2",
"created": 1433601654,
"url": "http://www.reddit.com/r/Charleston/comments/38smg2/looking_for_a_flat_downtown/",
"author_flair_text": null,
"title": "Looking for a flat downtown!",
"created_utc": 1433598054,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38prh8",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Seanji6",
"media": null,
"score": 49,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 15,
"thumbnail": "http://b.thumbs.redditmedia.com/yk6RhALSdARgebvCaeUFP6KTofa-61o68OaprPXoxDE.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/38prh8/just_another_view_of_this_beautiful_place/",
"name": "t3_38prh8",
"created": 1433564452,
"url": "http://imgur.com/RK1MCAJ",
"author_flair_text": null,
"title": "Just another view of this beautiful place",
"created_utc": 1433535652,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 49
}
},
{
"kind": "t3",
"data": {
"domain": "twitter.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38oo8z",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Propane13",
"media": null,
"score": 19,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 23,
"thumbnail": "http://a.thumbs.redditmedia.com/KjlHfZag0N9SkgSOELpH2l9odReGdvVJlP4ns5J00X0.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/38oo8z/sonic_boom_felt_around_1145am/",
"name": "t3_38oo8z",
"created": 1433524360,
"url": "https://twitter.com/HolyCitySinner/status/606852800144908289",
"author_flair_text": null,
"title": "Sonic boom felt around 11:45am?",
"created_utc": 1433520760,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 19
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey redditors of Charleston! \nSo I am new in town, just moved here about 3 weeks ago for an internship, and will be in the U.S. For a year. My commute is about 45-60mins each way and I have come to realize that having a car would make my life so much easier while im here. So I would like to ask you if you had any recommendations or tips on what kind of car I should be looking at (for ~$2500 max) and if you have any good experiences with specific dealerships?\nAlso, bonus question: any recommendations for places to see or things to do (something other than what you find googling &amp;quot;things to do in charleston&amp;quot;) to get to experience the American culture, or how/where to meet cool people around here?&lt;/p&gt;\n\n&lt;p&gt;I appriciate all comments and suggestions, thanks!&lt;/p&gt;\n\n&lt;p&gt;P.S. Im 25yrs old, just graduated from university, from Iceland.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hey redditors of Charleston! \nSo I am new in town, just moved here about 3 weeks ago for an internship, and will be in the U.S. For a year. My commute is about 45-60mins each way and I have come to realize that having a car would make my life so much easier while im here. So I would like to ask you if you had any recommendations or tips on what kind of car I should be looking at (for ~$2500 max) and if you have any good experiences with specific dealerships?\nAlso, bonus question: any recommendations for places to see or things to do (something other than what you find googling \"things to do in charleston\") to get to experience the American culture, or how/where to meet cool people around here?\n\nI appriciate all comments and suggestions, thanks!\n\nP.S. Im 25yrs old, just graduated from university, from Iceland.\n",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38qi6i",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "DanniKongur",
"media": null,
"score": 4,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 12,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38qi6i/new_in_town_and_need_advice/",
"name": "t3_38qi6i",
"created": 1433550819,
"url": "http://www.reddit.com/r/Charleston/comments/38qi6i/new_in_town_and_need_advice/",
"author_flair_text": null,
"title": "New in town and need advice",
"created_utc": 1433547219,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 4
}
},
{
"kind": "t3",
"data": {
"domain": "imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38qifv",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "CasterBaiter",
"media": null,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 7,
"thumbnail": "http://a.thumbs.redditmedia.com/MWoaK8eWfy7935d0BxkirO5a1YyUgetqjGo39oWEZt0.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/38qifv/can_anyone_help_me_identify_this_local_artist_and/",
"name": "t3_38qifv",
"created": 1433576141,
"url": "http://imgur.com/KdTyKmm",
"author_flair_text": null,
"title": "Can anyone help me identify this local artist and the name of the print? Saw it in North Charleston this week and want one!",
"created_utc": 1433547341,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 3
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I will be visiting the city in September and it will be my honeymoon. My fiance and my self just want to rent a jeep. I drive an XJ, but she wants to just rent a wrangler for a week and drive around. We&amp;#39;re staying on kiawah island, so that&amp;#39;s mainly why I suppose. We&amp;#39;re driving from east Tennessee so anywhere on the way would work too. Back to the question, is there ANYWHERE near there that rents jeeps. I know it&amp;#39;s like 30 miles from where we&amp;#39;re staying, but it would mean the world to her to just drive a wrangler. Thanks for any and all help!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I will be visiting the city in September and it will be my honeymoon. My fiance and my self just want to rent a jeep. I drive an XJ, but she wants to just rent a wrangler for a week and drive around. We're staying on kiawah island, so that's mainly why I suppose. We're driving from east Tennessee so anywhere on the way would work too. Back to the question, is there ANYWHERE near there that rents jeeps. I know it's like 30 miles from where we're staying, but it would mean the world to her to just drive a wrangler. Thanks for any and all help!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38rcfr",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "overshotbeatle",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 2,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/38rcfr/honeymoon_questionvehicle_related/",
"name": "t3_38rcfr",
"created": 1433566327,
"url": "http://www.reddit.com/r/Charleston/comments/38rcfr/honeymoon_questionvehicle_related/",
"author_flair_text": null,
"title": "Honeymoon question(vehicle related)",
"created_utc": 1433562727,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
}
],
"after": "t3_38rcfr",
"before": null
}
}
