module.exports = [
  {
    Title: "The Other Guys",
    Year: "2010",
    Rated: "PG-13",
    Released: "06 Aug 2010",
    Runtime: "107 min",
    Genre: "Action, Comedy, Crime",
    Director: "Adam McKay",
    Writer: "Adam McKay, Chris Henchy",
    Actors: "Will Ferrell, Derek Jeter, Mark Wahlberg, Eva Mendes",
    Plot: "Terry Hoitz's past mistakes in the line of duty and Allen Gamble's reluctance to take risks have landed them the roles of the \"Other Guys\", disgraced New York City police detectives relegated to filling out paperwork for cocky hero cops Danson and Highsmith. The mismatched duo must look past their differences when they take on a high-profile investigation of shady capitalist David Ershon and attempt to fill the shoes of the notoriously reckless officers they idolize.",
    Language: "English",
    Country: "USA",
    Awards: "3 wins & 13 nominations.",
    Poster: "http://ia.media-imdb.com/images/M/MV5BMTc0NDQzNTA2Ml5BMl5BanBnXkFtZTcwNzI2OTQzMw@@._V1_SX300.jpg",
    Metascore: "64",
    imdbRating: "6.6",
    imdbVotes: "168,145",
    imdbID: "tt1386588",
    Type: "movie",
    Response: "True"
  },
  {
    Title: "Jaws",
    Year: "1975",
    Rated: "PG",
    Released: "20 Jun 1975",
    Runtime: "124 min",
    Genre: "Drama, Thriller",
    Director: "Steven Spielberg",
    Writer: "Peter Benchley (screenplay), Carl Gottlieb (screenplay), Peter Benchley (based on the novel by)",
    Actors: "Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary",
    Plot: "It's a hot summer on Amity Island, a small community whose main business is its beaches. When new Sheriff Martin Brody discovers the remains of a shark attack victim, his first inclination is to close the beaches to swimmers. This doesn't sit well with Mayor Larry Vaughn and several of the local businessmen. Brody backs down to his regret as that weekend a young boy is killed by the predator. The dead boy's mother puts out a bounty on the shark and Amity is soon swamped with amateur hunters and fisherman hoping to cash in on the reward. A local fisherman with much experience hunting sharks, Quint, offers to hunt down the creature for a hefty fee. Soon Quint, Brody and Matt Hooper from the Oceanographic Institute are at sea hunting the Great White shark. As Brody succinctly surmises after their first encounter with the creature, they're going to need a bigger boat.",
    Language: "English",
    Country: "USA",
    Awards: "Won 3 Oscars. Another 10 wins & 14 nominations.",
    Poster: "http://ia.media-imdb.com/images/M/MV5BNDcxODkyMjY4MF5BMl5BanBnXkFtZTgwOTk5NTc5MDE@._V1_SX300.jpg",
    Metascore: "79",
    imdbRating: "8.1",
    imdbVotes: "352,931",
    imdbID: "tt0073195",
    Type: "movie",
    Response: "True"
  },
  {
    Title: "King Kong",
    Year: "2005",
    Rated: "PG-13",
    Released: "14 Dec 2005",
    Runtime: "187 min",
    Genre: "Action, Adventure, Drama",
    Director: "Peter Jackson",
    Writer: "Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay), Merian C. Cooper (based on a story by), Edgar Wallace (based on a story by)",
    Actors: "Naomi Watts, Jack Black, Adrien Brody, Thomas Kretschmann",
    Plot: "Carl Denham needs to finish his movie and has the perfect location; Skull Island. But he still needs to find a leading lady. This 'soon-to-be-unfortunate' soul is Ann Darrow. No one knows what they will encounter on this island and why it is so mysterious, but once they reach it, they will soon find out. Living on this hidden island is a giant gorilla and this beast now has Ann is its grasps. Carl and Ann's new love, Jack Driscoll must travel through the jungle looking for Kong and Ann, whilst avoiding all sorts of creatures and beasts. But Carl has another plan in mind.",
    Language: "English",
    Country: "New Zealand, USA, Germany",
    Awards: "Won 3 Oscars. Another 39 wins & 66 nominations.",
    Poster: "http://ia.media-imdb.com/images/M/MV5BMTgzODQwNjAwOV5BMl5BanBnXkFtZTcwMDA4MDA0MQ@@._V1_SX300.jpg",
    Metascore: "N/A",
    imdbRating: "7.3",
    imdbVotes: "287,819",
    imdbID: "tt0360717",
    Type: "movie",
    Response: "True"
  },
  {
    Title: "Django Unchained",
    Year: "2012",
    Rated: "R",
    Released: "25 Dec 2012",
    Runtime: "165 min",
    Genre: "Western",
    Director: "Quentin Tarantino",
    Writer: "Quentin Tarantino",
    Actors: "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington",
    Plot: "Former dentist, Dr. King Schultz, buys the freedom of a slave, Django, and trains him with the intent to make him his deputy bounty hunter. Instead, he is led to the site of Django's wife who is under the hands of Calvin Candie, a ruthless plantation owner.",
    Language: "English, German, French",
    Country: "USA",
    Awards: "Won 2 Oscars. Another 65 wins & 105 nominations.",
    Poster: "http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
    Metascore: "81",
    imdbRating: "8.5",
    imdbVotes: "777,356",
    imdbID: "tt1853728",
    Type: "movie",
    Response: "True"
  },
  {
    Title: "Drive",
    Year: "2011",
    Rated: "R",
    Released: "16 Sep 2011",
    Runtime: "100 min",
    Genre: "Crime, Drama",
    Director: "Nicolas Winding Refn",
    Writer: "Hossein Amini (screenplay), James Sallis (book)",
    Actors: "Ryan Gosling, Carey Mulligan, Bryan Cranston, Albert Brooks",
    Plot: "A mysterious man who has multiple jobs as a garage mechanic, a Hollywood stuntman and a getaway driver seems to be trying to escape his shady past as he falls for his neighbor - whose husband is in prison and who's looking after her child alone. Meanwhile, his garage mechanic boss is trying to set up a race team using gangland money, which implicates our driver as he is to be used as the race team's main driver. Our hero gets more than he bargained for when he meets the man who is married to the woman he loves.",
    Language: "English, Spanish",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 80 wins & 124 nominations.",
    Poster: "http://ia.media-imdb.com/images/M/MV5BOTM1ODQ0Nzc4NF5BMl5BanBnXkFtZTcwMTM0MjQyNg@@._V1_SX300.jpg",
    Metascore: "78",
    imdbRating: "7.8",
    imdbVotes: "387,708",
    imdbID: "tt0780504",
    Type: "movie",
    Response: "True"
  },
  {
    Title: "Pulp Fiction",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "154 min",
    Genre: "Crime, Drama",
    Director: "Quentin Tarantino",
    Writer: "Quentin Tarantino (story), Roger Avary (story), Quentin Tarantino",
    Actors: "Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta",
    Plot: "Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
    Language: "English, Spanish, French",
    Country: "USA",
    Awards: "Won 1 Oscar. Another 63 wins & 47 nominations.",
    Poster: "http://ia.media-imdb.com/images/M/MV5BMjE0ODk2NjczOV5BMl5BanBnXkFtZTYwNDQ0NDg4._V1_SX300.jpg",
    Metascore: "94",
    imdbRating: "8.9",
    imdbVotes: "1,132,720",
    imdbID: "tt0110912",
    Type: "movie",
    Response: "True"
  },
  {
    Title: "Taken",
    Year: "2008",
    Rated: "PG-13",
    Released: "30 Jan 2009",
    Runtime: "93 min",
    Genre: "Action, Thriller",
    Director: "Pierre Morel",
    Writer: "Luc Besson, Robert Mark Kamen",
    Actors: "Liam Neeson, Maggie Grace, Leland Orser, Jon Gries",
    Plot: "Seventeen year-old Kim is the pride and joy of her father Bryan Mills. Bryan is a retired agent who left the Central Intelligence Agency to be near Kim in California. Kim lives with her mother Lenore and her wealthy stepfather Stuart. Kim manages to convince her reluctant father to allow her to travel to Paris with her friend Amanda. When the girls arrive in Paris they share a cab with a stranger named Peter, and Amanda lets it slip that they are alone in Paris. Using this information an Albanian gang of human traffickers kidnaps the girls. Kim barely has time to call her father and give him information. Her father gets to speak briefly to one of the kidnappers and he promises to kill the kidnappers if they do not let his daughter go free. The kidnapper wishes him \"good luck,\" so Bryan Mills travels to Paris to search for his daughter and her friend.",
    Language: "English, French, Albanian, Arabic",
    Country: "France",
    Awards: "3 wins & 1 nomination.",
    Poster: "http://ia.media-imdb.com/images/M/MV5BMTM4NzQ0OTYyOF5BMl5BanBnXkFtZTcwMDkyNjQyMg@@._V1_SX300.jpg",
    Metascore: "50",
    imdbRating: "7.9",
    imdbVotes: "438,537",
    imdbID: "tt0936501",
    Type: "movie",
    Response: "True"
  },
  {
    Title: "Interstellar",
    Year: "2014",
    Rated: "PG-13",
    Released: "07 Nov 2014",
    Runtime: "169 min",
    Genre: "Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan",
    Actors: "Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow",
    Plot: "In the near future, Earth has been devastated by drought and famine, causing a scarcity in food and extreme changes in climate. When humanity is facing extinction, a mysterious rip in the space-time continuum is discovered, giving mankind the opportunity to widen its lifespan. A group of explorers must travel beyond our solar system in search of a planet that can sustain life. The crew of the Endurance are required to think bigger and go further than any human in history as they embark on an interstellar voyage into the unknown. Coop, the pilot of the Endurance, must decide between seeing his children again and the future of the human race.",
    Language: "English",
    Country: "USA, UK, Canada",
    Awards: "Won 1 Oscar. Another 38 wins & 103 nominations.",
    Poster: "http://ia.media-imdb.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg",
    Metascore: "74",
    imdbRating: "8.7",
    imdbVotes: "645,963",
    imdbID: "tt0816692",
    Type: "movie",
    Response: "True"
  }
];
