var redditData = {
"kind": "Listing",
"data": {
"modhash": "n9rbw8p0f1e5ed205b798b4976ea52a07d2eede1c746223125",
"children": [
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Welcome to our new &lt;strong&gt;weekly post&lt;/strong&gt; where we discuss any events or activities taking place this weekend in the Charleston area. You can find events by checking &lt;a href=\"http://www.charlestoncitypaper.com/charleston/EventSearch?narrowByDate=This%20Weekend\"&gt;Charleston City Paper&lt;/a&gt;, &lt;a href=\"http://chsbeer.org/events\"&gt;CHSBeer&lt;/a&gt;,  &lt;a href=\"http://www.holycitysinner.com/events/\"&gt;HolyCitySinner&lt;/a&gt;, &lt;a href=\"http://www.postandcourier.com/section/search&amp;amp;facet.filter=Keywords:Things%20to%20Do\"&gt;Post &amp;amp; Courier&lt;/a&gt;, or &lt;a href=\"http://www.charlestoncvb.com/visitors/events_news/charleston-events/\"&gt;Charleston CVB&lt;/a&gt;. Please post a link to an event page for additional information (if possible).&lt;/p&gt;\n\n&lt;p&gt;The goal is simple: to generate some discussion, learn about what&amp;#39;s happening in the area, arrange impromptu meetups, and maybe help out anyone visiting for the weekend.&lt;/p&gt;\n\n&lt;p&gt;Thanks for participating! Any questions, &lt;a href=\"https://www.reddit.com/message/compose?to=%2Fr%2Fcharleston\"&gt;please ask the mods&lt;/a&gt;.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Welcome to our new **weekly post** where we discuss any events or activities taking place this weekend in the Charleston area. You can find events by checking [Charleston City Paper](http://www.charlestoncitypaper.com/charleston/EventSearch?narrowByDate=This%20Weekend), [CHSBeer](http://chsbeer.org/events),  [HolyCitySinner](http://www.holycitysinner.com/events/), [Post &amp; Courier](http://www.postandcourier.com/section/search&amp;facet.filter=Keywords:Things%20to%20Do), or [Charleston CVB](http://www.charlestoncvb.com/visitors/events_news/charleston-events/). Please post a link to an event page for additional information (if possible).\n\nThe goal is simple: to generate some discussion, learn about what's happening in the area, arrange impromptu meetups, and maybe help out anyone visiting for the weekend.\n\nThanks for participating! Any questions, [please ask the mods](https://www.reddit.com/message/compose?to=%2Fr%2Fcharleston).\n",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": "TGIF!",
"id": "37pc75",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "AutoModerator",
"media": null,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": "tgif",
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37pc75",
"permalink": "/r/Charleston/comments/37pc75/weekend_roundup_may_29_2015/",
"stickied": true,
"created": 1432897346,
"url": "http://www.reddit.com/r/Charleston/comments/37pc75/weekend_roundup_may_29_2015/",
"author_flair_text": "Robot Overlord",
"title": "Weekend Roundup! May 29, 2015",
"created_utc": 1432893746,
"ups": 6,
"num_comments": 3,
"visited": false,
"num_reports": null,
"distinguished": "moderator"
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I went to a little roadside cinderblock shack in Swansea, and man, it was amazing! This is coming from someone who denies BBQ cannot exist outside the borders of NC.&lt;/p&gt;\n\n&lt;p&gt;Is there similar around Charleston somewhere?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I went to a little roadside cinderblock shack in Swansea, and man, it was amazing! This is coming from someone who denies BBQ cannot exist outside the borders of NC.\n\nIs there similar around Charleston somewhere?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "382ij0",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "fortfive",
"media": null,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_382ij0",
"permalink": "/r/Charleston/comments/382ij0/wiki_and_search_are_silent_so_i_ask_what_is_the/",
"stickied": false,
"created": 1433187314,
"url": "http://www.reddit.com/r/Charleston/comments/382ij0/wiki_and_search_are_silent_so_i_ask_what_is_the/",
"author_flair_text": null,
"title": "Wiki and Search are silent, so I ask, What is the best Soul Food and/or Country Cooking?",
"created_utc": 1433158514,
"ups": 6,
"num_comments": 8,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37znt9",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "maowmeowmaow",
"media": null,
"score": 25,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/t5rxMiwnteJ83c-_bGHUG-mFWks0yx1jDBPg0w1mu9U.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": false,
"name": "t3_37znt9",
"permalink": "/r/Charleston/comments/37znt9/help_moved_to_ladson_cat_got_out_details_in/",
"stickied": false,
"created": 1433129321,
"url": "http://imgur.com/jZHbMsM",
"author_flair_text": null,
"title": "Help! moved to Ladson, cat got out. Details in comments!",
"created_utc": 1433100521,
"ups": 25,
"num_comments": 11,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hi guys, I&amp;#39;ve had enough apartment living and would like to move to a house. I&amp;#39;m not interested in buying right now - the markets in areas I&amp;#39;m interested in seem overpriced. I&amp;#39;ve been watching craigslist and zillow and there hasn&amp;#39;t been a whole lot coming available (I&amp;#39;m interested in park circle, wagener terrace area, or avondale).  &lt;/p&gt;\n\n&lt;p&gt;Are there alternatives to zillow and craigslist that are used for charleston rentals? Do some people just put up &amp;#39;for rent&amp;#39; signs - is it worth walking around these neighborhoods? Is there a certain time of year that rentals tend to become available? Any advice for finding a rental is appreciated. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hi guys, I've had enough apartment living and would like to move to a house. I'm not interested in buying right now - the markets in areas I'm interested in seem overpriced. I've been watching craigslist and zillow and there hasn't been a whole lot coming available (I'm interested in park circle, wagener terrace area, or avondale).  \n\nAre there alternatives to zillow and craigslist that are used for charleston rentals? Do some people just put up 'for rent' signs - is it worth walking around these neighborhoods? Is there a certain time of year that rentals tend to become available? Any advice for finding a rental is appreciated. ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3809ex",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "nebent",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_3809ex",
"permalink": "/r/Charleston/comments/3809ex/finding_rental_houses_in_charleston/",
"stickied": false,
"created": 1433138682,
"url": "http://www.reddit.com/r/Charleston/comments/3809ex/finding_rental_houses_in_charleston/",
"author_flair_text": null,
"title": "Finding rental houses in charleston",
"created_utc": 1433109882,
"ups": 5,
"num_comments": 3,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Long shot, but I&amp;#39;m a Data Science student at CofC with project management experience but I lack programming experience which has been keeping me from getting an internship over the summer. &lt;/p&gt;\n\n&lt;p&gt;Anyone know of someone who has a paid internship in which I can get some good experience? Thanks in advance.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Long shot, but I'm a Data Science student at CofC with project management experience but I lack programming experience which has been keeping me from getting an internship over the summer. \n\nAnyone know of someone who has a paid internship in which I can get some good experience? Thanks in advance.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "38061n",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "pchendley",
"media": null,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_38061n",
"permalink": "/r/Charleston/comments/38061n/internship_opportunities/",
"stickied": false,
"created": 1433137210,
"url": "http://www.reddit.com/r/Charleston/comments/38061n/internship_opportunities/",
"author_flair_text": null,
"title": "Internship opportunities",
"created_utc": 1433108410,
"ups": 3,
"num_comments": 1,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;With school out of the way we are starting back up regular Sunday meetings. If you are interested in learning yoyo, Kendama, diabolo, or another skill toy come hang out. Meetings are free and easy. Downtown at Marion square starting at 12 and going until we tire of each other. Peace looking forward to some new faces. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "With school out of the way we are starting back up regular Sunday meetings. If you are interested in learning yoyo, Kendama, diabolo, or another skill toy come hang out. Meetings are free and easy. Downtown at Marion square starting at 12 and going until we tire of each other. Peace looking forward to some new faces. ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37ygqq",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "WinstonPoonPhoenix",
"media": null,
"score": 9,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37ygqq",
"permalink": "/r/Charleston/comments/37ygqq/throw_charleston_the_yoyo_and_kendama_club/",
"stickied": false,
"created": 1433108506,
"url": "http://www.reddit.com/r/Charleston/comments/37ygqq/throw_charleston_the_yoyo_and_kendama_club/",
"author_flair_text": null,
"title": "Throw Charleston - The yoyo and Kendama club",
"created_utc": 1433079706,
"ups": 9,
"num_comments": 2,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Just moved here a little over a month ago &amp;amp; I work at the top of N Market but don&amp;#39;t really know some good tips for parking &amp;amp; not having to walk 15 minutes. &lt;/p&gt;\n\n&lt;p&gt;The only place I&amp;#39;ve found in the BoA parking garage which is $20 a day because I work 8 hours a day.... &lt;/p&gt;\n\n&lt;p&gt;Any help? &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Just moved here a little over a month ago &amp; I work at the top of N Market but don't really know some good tips for parking &amp; not having to walk 15 minutes. \n\nThe only place I've found in the BoA parking garage which is $20 a day because I work 8 hours a day.... \n\nAny help? ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37zew9",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "cloudlight",
"media": null,
"score": 1,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37zew9",
"permalink": "/r/Charleston/comments/37zew9/so_i_work_on_n_market_st_need_help_with_parking/",
"stickied": false,
"created": 1433125345,
"url": "http://www.reddit.com/r/Charleston/comments/37zew9/so_i_work_on_n_market_st_need_help_with_parking/",
"author_flair_text": null,
"title": "So I work on N Market St &amp; need help with parking...",
"created_utc": 1433096545,
"ups": 1,
"num_comments": 6,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "youtube.com",
"banned_by": null,
"media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FtaPoeIQaOiQ%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DtaPoeIQaOiQ&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FtaPoeIQaOiQ%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"450\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 450
},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": {
"type": "youtube.com",
"oembed": {
"provider_url": "http://www.youtube.com/",
"description": "A deleted scene from Lilo &amp; Stitch. Lilo decides to vent her frustrations on some tourists.",
"title": "Lilo &amp; Stitch' deleted scene that tackled racism &amp; obnoxious tourists",
"url": "http://www.youtube.com/watch?v=taPoeIQaOiQ",
"author_name": "HeleZort",
"height": 450,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FtaPoeIQaOiQ%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DtaPoeIQaOiQ&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FtaPoeIQaOiQ%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"450\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"thumbnail_width": 480,
"version": "1.0",
"provider_name": "YouTube",
"thumbnail_url": "https://i.embed.ly/1/image?url=https%3A%2F%2Fi.ytimg.com%2Fvi%2FtaPoeIQaOiQ%2Fhqdefault.jpg&amp;key=b1e305db91cf4aa5a86b732cc9fffceb",
"type": "video",
"thumbnail_height": 360,
"author_url": "http://www.youtube.com/user/HeleZort"
}
},
"link_flair_text": null,
"id": "37wqxb",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "islandthyme",
"media": {
"type": "youtube.com",
"oembed": {
"provider_url": "http://www.youtube.com/",
"description": "A deleted scene from Lilo &amp; Stitch. Lilo decides to vent her frustrations on some tourists.",
"title": "Lilo &amp; Stitch' deleted scene that tackled racism &amp; obnoxious tourists",
"url": "http://www.youtube.com/watch?v=taPoeIQaOiQ",
"author_name": "HeleZort",
"height": 450,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FtaPoeIQaOiQ%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DtaPoeIQaOiQ&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FtaPoeIQaOiQ%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"450\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"thumbnail_width": 480,
"version": "1.0",
"provider_name": "YouTube",
"thumbnail_url": "https://i.ytimg.com/vi/taPoeIQaOiQ/hqdefault.jpg",
"type": "video",
"thumbnail_height": 360,
"author_url": "http://www.youtube.com/user/HeleZort"
}
},
"score": 15,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://a.thumbs.redditmedia.com/3PdUvy_xO6L0vuDzY3sOhEH2Wo5aKglce320o5WxRp0.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FtaPoeIQaOiQ%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DtaPoeIQaOiQ&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FtaPoeIQaOiQ%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"450\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 450
},
"saved": false,
"removal_reason": null,
"is_self": false,
"name": "t3_37wqxb",
"permalink": "/r/Charleston/comments/37wqxb/lilo_and_stitch_know_exactly_how_i_feel_this_time/",
"stickied": false,
"created": 1433063656,
"url": "https://www.youtube.com/watch?v=taPoeIQaOiQ",
"author_flair_text": null,
"title": "Lilo and Stitch know exactly how I feel this time of the year",
"created_utc": 1433034856,
"ups": 15,
"num_comments": 2,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m going to grad school at CofC in the fall for a Master&amp;#39;s in Accounting. I&amp;#39;m trying to get some experience this summer. I&amp;#39;ve been sending my resume into every job opening I see. When I say I&amp;#39;m not going to be able to work during the school year, they say they&amp;#39;re looking for someone to stay. Figured it was worth a shot, thanks Holy City! &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I'm going to grad school at CofC in the fall for a Master's in Accounting. I'm trying to get some experience this summer. I've been sending my resume into every job opening I see. When I say I'm not going to be able to work during the school year, they say they're looking for someone to stay. Figured it was worth a shot, thanks Holy City! ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37wq42",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "z007records",
"media": null,
"score": 7,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37wq42",
"permalink": "/r/Charleston/comments/37wq42/any_chance_theres_a_cpa_on_this_subreddit/",
"stickied": false,
"created": 1433063226,
"url": "http://www.reddit.com/r/Charleston/comments/37wq42/any_chance_theres_a_cpa_on_this_subreddit/",
"author_flair_text": null,
"title": "Any chance there's a CPA on this subreddit?",
"created_utc": 1433034426,
"ups": 7,
"num_comments": 6,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Following, &lt;a href=\"/u/SeymourGlas\"&gt;/u/SeymourGlas&lt;/a&gt; here is a link to the Wannamaker Movie Night schedule for the 2015 summer.  It is held at the North Charleston Wannamaker County Park. Admission is free with regular park admission of $1 per person. &lt;a href=\"http://www.ccprc.com/1667/Wannamaker-Movie-Night\"&gt;Movie Schedule&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;P.S. Anyway we could start a month schedule for events like this in the area? &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Following, /u/SeymourGlas here is a link to the Wannamaker Movie Night schedule for the 2015 summer.  It is held at the North Charleston Wannamaker County Park. Admission is free with regular park admission of $1 per person. [Movie Schedule](http://www.ccprc.com/1667/Wannamaker-Movie-Night)\n\nP.S. Anyway we could start a month schedule for events like this in the area? ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37v96c",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "champenguin",
"media": null,
"score": 8,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": 1433017319,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37v96c",
"permalink": "/r/Charleston/comments/37v96c/wannamaker_movie_night_summer_schedule/",
"stickied": false,
"created": 1433012897,
"url": "http://www.reddit.com/r/Charleston/comments/37v96c/wannamaker_movie_night_summer_schedule/",
"author_flair_text": null,
"title": "Wannamaker Movie Night Summer Schedule.",
"created_utc": 1433009297,
"ups": 8,
"num_comments": 2,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hi guys, I&amp;#39;m from the northeast but looking to make a drastic change in my life. I&amp;#39;ve been to Charleston before and liked it, so I&amp;#39;m planning to abruptly quit my job on Monday and move down there in a few weeks. I have no idea what I&amp;#39;m doing or if this is even a good idea, but I need to take this chance.\nSo I&amp;#39;m wondering if you could make any suggestions, whether it is about what neighborhoods to look at when looking on Craigslist (relatively safe ones), anything I should consider or know when doing this, and what prospects might be for someone with no contacts or connections there to randomly show up like this. I&amp;#39;ve also considered Atlanta, Nashville other possible destinations in case you are familiar with there too in comparison. Thanks Redditors&lt;/p&gt;\n\n&lt;p&gt;EDIT:\nI&amp;#39;ve 30 years old, have saved up a bit so I&amp;#39;ll be OK for a few months, but I&amp;#39;m also trying to be realistic and a bit stingy just so I don&amp;#39;t blow through my savings.\nI&amp;#39;m currently at a dead end type job with way too much free time, have been teaching myself programming (Python, if anyone randomly has job ideas and tips), and am ready to make a big change in my life.  I know I won&amp;#39;t be getting a job immediately and am motivated enough to work on a portfolio and continue learning web dev &amp;amp; programming.\nThat said, I&amp;#39;d appreciate if people would spare the pessimistic and unhelpful comments telling me to stay in the North, etc.\nThanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hi guys, I'm from the northeast but looking to make a drastic change in my life. I've been to Charleston before and liked it, so I'm planning to abruptly quit my job on Monday and move down there in a few weeks. I have no idea what I'm doing or if this is even a good idea, but I need to take this chance.\nSo I'm wondering if you could make any suggestions, whether it is about what neighborhoods to look at when looking on Craigslist (relatively safe ones), anything I should consider or know when doing this, and what prospects might be for someone with no contacts or connections there to randomly show up like this. I've also considered Atlanta, Nashville other possible destinations in case you are familiar with there too in comparison. Thanks Redditors\n\nEDIT:\nI've 30 years old, have saved up a bit so I'll be OK for a few months, but I'm also trying to be realistic and a bit stingy just so I don't blow through my savings.\nI'm currently at a dead end type job with way too much free time, have been teaching myself programming (Python, if anyone randomly has job ideas and tips), and am ready to make a big change in my life.  I know I won't be getting a job immediately and am motivated enough to work on a portfolio and continue learning web dev &amp; programming.\nThat said, I'd appreciate if people would spare the pessimistic and unhelpful comments telling me to stay in the North, etc.\nThanks!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37xe7o",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "kahwasaurus",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": 1433108890,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37xe7o",
"permalink": "/r/Charleston/comments/37xe7o/planning_a_random_move_to_charleston/",
"stickied": false,
"created": 1433076917,
"url": "http://www.reddit.com/r/Charleston/comments/37xe7o/planning_a_random_move_to_charleston/",
"author_flair_text": null,
"title": "Planning a random move to Charleston",
"created_utc": 1433048117,
"ups": 0,
"num_comments": 19,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;What a challenge it has been to relocate to Charleston from Atlanta. Made our decision to move there during dinner at Pane E Vino during a visit between Christmas and New Years. We made two subsequent trips to Charleston to scout for homes and hopefully sign a lease. Holy Crap!&lt;/p&gt;\n\n&lt;p&gt;This city is under seige. Every house we visited had at least 5 and sometimes 15 applications. Mount Pleasant, James Island and West Ashley. We made appointments to see houses and had them canceled because the place was rented before we could even show up. &lt;/p&gt;\n\n&lt;p&gt;We expect a slight price increase from our current home in Atlanta but it is $900 more. AND...it won&amp;#39;t be available until 9/1. &lt;/p&gt;\n\n&lt;p&gt;So, we are vagabonds until then. First stop Bluffton, SC for 30 days. Then? Who knows. &lt;/p&gt;\n\n&lt;p&gt;We are very excited about moving to Charleston. Our favorite city. I will need to make some connections and gain some local clients so if you know of any business that needs more internet presence, traffic or leads, I&amp;#39;d appreciate the heads up. &lt;/p&gt;\n\n&lt;p&gt;I have been a digital marketer for over 6 years with a long list of happy clients. PM for my LinkedIn if you are interested. &lt;/p&gt;\n\n&lt;p&gt;Finally, thanks to all the &lt;a href=\"/r/Charleston\"&gt;/r/Charleston&lt;/a&gt; redditors for their direct and indirect input. This subreddit has made it a little easier to gain some knowledge of the area. &lt;/p&gt;\n\n&lt;p&gt;Oh, we landed in West Ashley right next to the Stono River in a private little area. It will be awesome. Now, to get my sailboat moved...&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "What a challenge it has been to relocate to Charleston from Atlanta. Made our decision to move there during dinner at Pane E Vino during a visit between Christmas and New Years. We made two subsequent trips to Charleston to scout for homes and hopefully sign a lease. Holy Crap!\n\nThis city is under seige. Every house we visited had at least 5 and sometimes 15 applications. Mount Pleasant, James Island and West Ashley. We made appointments to see houses and had them canceled because the place was rented before we could even show up. \n\nWe expect a slight price increase from our current home in Atlanta but it is $900 more. AND...it won't be available until 9/1. \n\nSo, we are vagabonds until then. First stop Bluffton, SC for 30 days. Then? Who knows. \n\nWe are very excited about moving to Charleston. Our favorite city. I will need to make some connections and gain some local clients so if you know of any business that needs more internet presence, traffic or leads, I'd appreciate the heads up. \n\nI have been a digital marketer for over 6 years with a long list of happy clients. PM for my LinkedIn if you are interested. \n\nFinally, thanks to all the /r/Charleston redditors for their direct and indirect input. This subreddit has made it a little easier to gain some knowledge of the area. \n\nOh, we landed in West Ashley right next to the Stono River in a private little area. It will be awesome. Now, to get my sailboat moved...",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37wijq",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "beaglesbark2much",
"media": null,
"score": 1,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37wijq",
"permalink": "/r/Charleston/comments/37wijq/its_official_we_are_moving_to_charleston_and_we/",
"stickied": false,
"created": 1433059145,
"url": "http://www.reddit.com/r/Charleston/comments/37wijq/its_official_we_are_moving_to_charleston_and_we/",
"author_flair_text": null,
"title": "It's official! We are moving to Charleston. (And, we already have a leased signed so no questions about where to live...)",
"created_utc": 1433030345,
"ups": 1,
"num_comments": 3,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "abcnews4.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37s94r",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "QuitCallingNewsrooms",
"media": null,
"score": 19,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/zyG4FSx59hL0nZ0Ygq1JSIpwCeLvtNzvuRs2xr7SvUU.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": false,
"name": "t3_37s94r",
"permalink": "/r/Charleston/comments/37s94r/former_owners_say_they_might_know_who_taped_their/",
"stickied": false,
"created": 1432946789,
"url": "http://www.abcnews4.com/story/29178519/cas-dog-could-lose-tongue-after-muzzle-taped-shut-reward-offered-for-suspect-info",
"author_flair_text": null,
"title": "Former owners say they might know who taped their dog's mouth shut and left it in a ditch",
"created_utc": 1432943189,
"ups": 19,
"num_comments": 18,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "echl.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37r4p4",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Andy_Glass",
"media": null,
"score": 25,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/vQPcB0qf_yf5i1xO45VqqLZKdXLa3dbe6-yFFHrOL0s.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": false,
"name": "t3_37r4p4",
"permalink": "/r/Charleston/comments/37r4p4/support_the_south_carolina_stingrays_as_they/",
"stickied": false,
"created": 1432929129,
"url": "http://echl.com/schedule-announced-for-2015-kelly-cup-finals-p198092",
"author_flair_text": null,
"title": "Support the South Carolina Stingrays as they battle the Allen Americans in the Kelly Cup Finals!",
"created_utc": 1432925529,
"ups": 25,
"num_comments": 12,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37td9u",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "SmashBros4",
"media": null,
"score": 4,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37td9u",
"permalink": "/r/Charleston/comments/37td9u/any_competitive_melee_players_here/",
"stickied": false,
"created": 1432994434,
"url": "http://www.reddit.com/r/Charleston/comments/37td9u/any_competitive_melee_players_here/",
"author_flair_text": null,
"title": "Any competitive Melee players here?",
"created_utc": 1432965634,
"ups": 4,
"num_comments": 15,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Through the summer every Wednesday night you can go to Folly for a free movie, how cool is that? &lt;/p&gt;\n\n&lt;p&gt;Here is a link to the movies playing in &lt;a href=\"http://www.tidesfollybeach.com/news/view/beach_movie_night_june_july\"&gt;June/July&lt;/a&gt;\naaand here is the link for movies playing in &lt;a href=\"http://www.tidesfollybeach.com/news/view/beach_movie_night_july_august\"&gt;July/August&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Through the summer every Wednesday night you can go to Folly for a free movie, how cool is that? \n\nHere is a link to the movies playing in [June/July](http://www.tidesfollybeach.com/news/view/beach_movie_night_june_july)\naaand here is the link for movies playing in [July/August](http://www.tidesfollybeach.com/news/view/beach_movie_night_july_august)",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37prhc",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "SeymourGlas",
"media": null,
"score": 29,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37prhc",
"permalink": "/r/Charleston/comments/37prhc/my_sweet_charlestonians_dont_forget_about_beach/",
"stickied": false,
"created": 1432933300,
"url": "http://www.reddit.com/r/Charleston/comments/37prhc/my_sweet_charlestonians_dont_forget_about_beach/",
"author_flair_text": null,
"title": "My sweet Charlestonians! Don't forget about Beach Movie Night.",
"created_utc": 1432904500,
"ups": 29,
"num_comments": 13,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I definitely want to do the glow, night time paddle boarding with Charleston Paddlers but I was wondering what else is out there that not a lot of people know about. Cool spots, restaurants, bars... Something cute and unique to this area. Thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I definitely want to do the glow, night time paddle boarding with Charleston Paddlers but I was wondering what else is out there that not a lot of people know about. Cool spots, restaurants, bars... Something cute and unique to this area. Thanks!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37sfxo",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Holy_City_Sinner",
"media": null,
"score": 1,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37sfxo",
"permalink": "/r/Charleston/comments/37sfxo/unique_date_suggestions_for_the_charleston_or/",
"stickied": false,
"created": 1432950263,
"url": "http://www.reddit.com/r/Charleston/comments/37sfxo/unique_date_suggestions_for_the_charleston_or/",
"author_flair_text": null,
"title": "Unique date suggestions for the Charleston or surrounding area?",
"created_utc": 1432946663,
"ups": 1,
"num_comments": 4,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey everyone, looking for a little advice - if there&amp;#39;s a better subreddit to put this in, please let me know, but I thought asking locally would be a two birds, one stone sort of situation. This is a plea for advice from a loving wife for her seriously overworked and hardworking, loving husband. He doesn&amp;#39;t know I&amp;#39;m posting this, but is actively seeking a way out of the situation that he&amp;#39;s been in for over 15 years. I&amp;#39;m just trying to do everything I can to help him. Some of you may know him - we&amp;#39;ve hosted a few reddit meetups in the past, though it has been a while. &lt;/p&gt;\n\n&lt;p&gt;A little background: My husband has owned a successful commercial cleaning business since 1998. He has contracts with some of the local hospitals and warehouses providing things like pressure washing, janitorial, and window cleaning, and has a half dozen employees currently, though he&amp;#39;s had up to 30 employees on the payroll in the past. For so many years, he&amp;#39;s been the sales guy, the accounting guy, the human resources guy, the labor guy, etc. etc. etc. He&amp;#39;s been working 80-90+ hour weeks for so long, doing a LOT of physical labor because that&amp;#39;s just what he has to do to make ends meet, and he&amp;#39;s so, so burnt out.  The type of people that traditionally respond to general labor and janitorial work on job posting sites are not the most reliable, unfortunately, so he&amp;#39;s constantly having to cover for people not showing up for their job in the middle of the night, constantly having to rearrange his schedule, constantly having to hire new people, and it is wearing on him. He&amp;#39;s in his late thirties, and though he&amp;#39;s still young, the physical toll of the job is really wearing on him - if he gets injured, which occasionally happens, there&amp;#39;s no opportunity to rest the injury - it&amp;#39;s just a cycle that feels impossible to get out of. He also has a range of interests including singing and songwriting and making things - but he can never pursue anything because he&amp;#39;s so exhausted, he just crashes when he gets home. He has children, and gives them and me every ounce of his energy that isn&amp;#39;t going to his work. It&amp;#39;s hard to watch such a good person, a relatively young person, looking so weary and burnt out all of the time, but of course, he&amp;#39;s still giving it his all. &lt;/p&gt;\n\n&lt;p&gt;We live relatively frugally, and I, pregnant with our (surprise) second child, work a number of smaller jobs as well as take care of our 2 year old. All that said, my husband has to cover child support and alimony from a previous marriage, so he has to make a certain income to make ends meet. It&amp;#39;s not super crazy, probably somewhere around 40-50k, and with his level of experience in managing, sales, hiring, etc, I think he&amp;#39;s qualified to make that level of income. He&amp;#39;s the most likable, hard working, friendly, genuine person you&amp;#39;ll ever meet (at least that&amp;#39;s what a bunch of people have told me throughout our relationship), and would be an incredible asset to any company.  &lt;/p&gt;\n\n&lt;p&gt;Here&amp;#39;s the help I need, and I appreciate anyone who has read this far and willing to offer any advice - is there a type of company that will take someone like my husband and help him write a resume and connect him with job openings that fit his certain level of skill? If so, any recommendations for a local company that can do this? I think this is called a job recruiter, but it seems like that&amp;#39;s more for companies to use, vs. individuals, but maybe I&amp;#39;m wrong. Second, if anyone has any suggestions on job openings or companies hiring that could fit with his skill set as mentioned here, I&amp;#39;d be forever grateful if you shared it. He&amp;#39;s more than willing to do this search himself, and has, but I thought I&amp;#39;d reach out to the community as a cover-all-bases situation. &lt;/p&gt;\n\n&lt;p&gt;Thank you, thank you, thank you for reading this. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hey everyone, looking for a little advice - if there's a better subreddit to put this in, please let me know, but I thought asking locally would be a two birds, one stone sort of situation. This is a plea for advice from a loving wife for her seriously overworked and hardworking, loving husband. He doesn't know I'm posting this, but is actively seeking a way out of the situation that he's been in for over 15 years. I'm just trying to do everything I can to help him. Some of you may know him - we've hosted a few reddit meetups in the past, though it has been a while. \n\nA little background: My husband has owned a successful commercial cleaning business since 1998. He has contracts with some of the local hospitals and warehouses providing things like pressure washing, janitorial, and window cleaning, and has a half dozen employees currently, though he's had up to 30 employees on the payroll in the past. For so many years, he's been the sales guy, the accounting guy, the human resources guy, the labor guy, etc. etc. etc. He's been working 80-90+ hour weeks for so long, doing a LOT of physical labor because that's just what he has to do to make ends meet, and he's so, so burnt out.  The type of people that traditionally respond to general labor and janitorial work on job posting sites are not the most reliable, unfortunately, so he's constantly having to cover for people not showing up for their job in the middle of the night, constantly having to rearrange his schedule, constantly having to hire new people, and it is wearing on him. He's in his late thirties, and though he's still young, the physical toll of the job is really wearing on him - if he gets injured, which occasionally happens, there's no opportunity to rest the injury - it's just a cycle that feels impossible to get out of. He also has a range of interests including singing and songwriting and making things - but he can never pursue anything because he's so exhausted, he just crashes when he gets home. He has children, and gives them and me every ounce of his energy that isn't going to his work. It's hard to watch such a good person, a relatively young person, looking so weary and burnt out all of the time, but of course, he's still giving it his all. \n\nWe live relatively frugally, and I, pregnant with our (surprise) second child, work a number of smaller jobs as well as take care of our 2 year old. All that said, my husband has to cover child support and alimony from a previous marriage, so he has to make a certain income to make ends meet. It's not super crazy, probably somewhere around 40-50k, and with his level of experience in managing, sales, hiring, etc, I think he's qualified to make that level of income. He's the most likable, hard working, friendly, genuine person you'll ever meet (at least that's what a bunch of people have told me throughout our relationship), and would be an incredible asset to any company.  \n\nHere's the help I need, and I appreciate anyone who has read this far and willing to offer any advice - is there a type of company that will take someone like my husband and help him write a resume and connect him with job openings that fit his certain level of skill? If so, any recommendations for a local company that can do this? I think this is called a job recruiter, but it seems like that's more for companies to use, vs. individuals, but maybe I'm wrong. Second, if anyone has any suggestions on job openings or companies hiring that could fit with his skill set as mentioned here, I'd be forever grateful if you shared it. He's more than willing to do this search himself, and has, but I thought I'd reach out to the community as a cover-all-bases situation. \n\nThank you, thank you, thank you for reading this. ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37pwsy",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "canibuyatrowel",
"media": null,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37pwsy",
"permalink": "/r/Charleston/comments/37pwsy/need_advice_on_job_searchplacementrecruitment_for/",
"stickied": false,
"created": 1432910840,
"url": "http://www.reddit.com/r/Charleston/comments/37pwsy/need_advice_on_job_searchplacementrecruitment_for/",
"author_flair_text": null,
"title": "Need advice on job search/placement/recruitment for overworked husband, please! :)",
"created_utc": 1432907240,
"ups": 3,
"num_comments": 12,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;The box office is sold out, and they recommended checking for cancelations, which I will, but I know reddit has come through for people in crazy ways so I thought I&amp;#39;d give it a shot.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "The box office is sold out, and they recommended checking for cancelations, which I will, but I know reddit has come through for people in crazy ways so I thought I'd give it a shot.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37rbml",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "nutsocharles",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37rbml",
"permalink": "/r/Charleston/comments/37rbml/long_shot_but_does_anyone_have_unneeded_tickets/",
"stickied": false,
"created": 1432931933,
"url": "http://www.reddit.com/r/Charleston/comments/37rbml/long_shot_but_does_anyone_have_unneeded_tickets/",
"author_flair_text": null,
"title": "Long shot, but does anyone have unneeded tickets to any of the remaining performances of Veremonda? (Spoleto)",
"created_utc": 1432928333,
"ups": 0,
"num_comments": 4,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;My boyfriend and I are visiting for his Birthday. We are going to Husk for his birthday, but we have a few days to take in the city. What restaurants, sites, activities would you recommend? &lt;/p&gt;\n\n&lt;p&gt;Also, how well is Uber taking off in the city? We will be staying in a place near Hominy Grill and how difficult it will be to get around.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "My boyfriend and I are visiting for his Birthday. We are going to Husk for his birthday, but we have a few days to take in the city. What restaurants, sites, activities would you recommend? \n\nAlso, how well is Uber taking off in the city? We will be staying in a place near Hominy Grill and how difficult it will be to get around.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37slf1",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Nifferplz",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37slf1",
"permalink": "/r/Charleston/comments/37slf1/visiting_june_18th_to_21st_looking_for_activities/",
"stickied": false,
"created": 1432953038,
"url": "http://www.reddit.com/r/Charleston/comments/37slf1/visiting_june_18th_to_21st_looking_for_activities/",
"author_flair_text": null,
"title": "Visiting June 18th to 21st. Looking for activities, food, drink, etc.",
"created_utc": 1432949438,
"ups": 0,
"num_comments": 2,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "postandcourier.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37nrrw",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "tidalrip",
"media": null,
"score": 11,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/Fb2FSb4mrc-fQTBPcp-8BYrRccuAB6ebVpILWTKm5as.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": false,
"name": "t3_37nrrw",
"permalink": "/r/Charleston/comments/37nrrw/kiawah_developers_win_new_permit_for_captain_sams/",
"stickied": false,
"created": 1432861947,
"url": "http://www.postandcourier.com/article/20150526/PC16/150529429/1177/kiawah-developers-win-new-permit-for-captain-sam-x2019-s-spit",
"author_flair_text": null,
"title": "Kiawah developers win new permit for Captain Sam’s Spit, Beachwalker Park may move",
"created_utc": 1432858347,
"ups": 11,
"num_comments": 20,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "postandcourier.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37l2z5",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Dr_Leo_1964",
"media": null,
"score": 31,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/oxrCR4eqQ1acLC84nS4AXgjhjoO_qnTHKJkV-RCQjyo.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": false,
"name": "t3_37l2z5",
"permalink": "/r/Charleston/comments/37l2z5/iop_councilman_urges_area_support_of_plastic_bag/",
"stickied": false,
"created": 1432819514,
"url": "http://www.postandcourier.com/article/20150527/PC16/150529359/1006/",
"author_flair_text": null,
"title": "IOP councilman urges area support of plastic bag ban",
"created_utc": 1432815914,
"ups": 31,
"num_comments": 20,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Big loud shake&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Big loud shake",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37mjd0",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "brophyd",
"media": null,
"score": 7,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37mjd0",
"permalink": "/r/Charleston/comments/37mjd0/anyone_feel_hear_the_loud_boom_shake_around_goose/",
"stickied": false,
"created": 1432842373,
"url": "http://www.reddit.com/r/Charleston/comments/37mjd0/anyone_feel_hear_the_loud_boom_shake_around_goose/",
"author_flair_text": null,
"title": "Anyone feel hear the loud boom shake around Goose Creek?",
"created_utc": 1432838773,
"ups": 7,
"num_comments": 4,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;So I have been doing some research on floating the Edisto River, because this is something I have always wanted to do. &lt;/p&gt;\n\n&lt;p&gt;One thing I can&amp;#39;t seem to find information on is River float pumps. Previously, when going river floating in other places, there have always been nozzles at the location to blow up the floats. Is there a drop off point on the Edisto that has this? &lt;/p&gt;\n\n&lt;p&gt;Also, any insider tips about Edisto floating in general are appreciated!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "So I have been doing some research on floating the Edisto River, because this is something I have always wanted to do. \n\nOne thing I can't seem to find information on is River float pumps. Previously, when going river floating in other places, there have always been nozzles at the location to blow up the floats. Is there a drop off point on the Edisto that has this? \n\nAlso, any insider tips about Edisto floating in general are appreciated!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37lhvy",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "patriche",
"media": null,
"score": 12,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37lhvy",
"permalink": "/r/Charleston/comments/37lhvy/edisto_river_floating_question/",
"stickied": false,
"created": 1432826548,
"url": "http://www.reddit.com/r/Charleston/comments/37lhvy/edisto_river_floating_question/",
"author_flair_text": null,
"title": "Edisto River floating question",
"created_utc": 1432822948,
"ups": 12,
"num_comments": 19,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;So this weekend I&amp;#39;ll be doing my first river float down the Edisto River, and I was wondering - what do I need to know about it? Should I be wary of alligators/snakes/etc? Where do people typically take off from and where do they typically get off at? Are you allowed to bring alcohol or is it possible I could get a fine?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "So this weekend I'll be doing my first river float down the Edisto River, and I was wondering - what do I need to know about it? Should I be wary of alligators/snakes/etc? Where do people typically take off from and where do they typically get off at? Are you allowed to bring alcohol or is it possible I could get a fine?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37luw4",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "clumsywords34",
"media": null,
"score": 8,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": true,
"name": "t3_37luw4",
"permalink": "/r/Charleston/comments/37luw4/questions_about_floating_down_the_river/",
"stickied": false,
"created": 1432832105,
"url": "http://www.reddit.com/r/Charleston/comments/37luw4/questions_about_floating_down_the_river/",
"author_flair_text": null,
"title": "Questions about floating down the river",
"created_utc": 1432828505,
"ups": 8,
"num_comments": 3,
"visited": false,
"num_reports": null,
"distinguished": null
}
},
{
"kind": "t3",
"data": {
"domain": "charlestonscene.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "37lryx",
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "TheKoG",
"media": null,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"thumbnail": "http://b.thumbs.redditmedia.com/8M4MR83NGn7VYVnBVLKLJGl0MbkE2aXzS6w6d8rilOY.jpg",
"subreddit_id": "t5_2qi6h",
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"mod_reports": [],
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"is_self": false,
"name": "t3_37lryx",
"permalink": "/r/Charleston/comments/37lryx/ellen_degeneres_new_dating_show_calls_for_singles/",
"stickied": false,
"created": 1432830816,
"url": "http://www.charlestonscene.com/article/20150527/CS/150529377/ellen-degeneres-x2019-new-dating-show-calls-for-singles-in-carolinas",
"author_flair_text": null,
"title": "Ellen DeGeneres’ new dating show calls for singles in Carolinas",
"created_utc": 1432827216,
"ups": 6,
"num_comments": 0,
"visited": false,
"num_reports": null,
"distinguished": null
}
}
],
"after": "t3_37lryx",
"before": null
}
}
